In [1]:
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))

if project_root not in sys.path:
    sys.path.insert(0, project_root)
from src.data.load_data import get_all_returns_fundamental
from src.data.compute_zscores import compute_fundamental_zscores
from src.data.load_data import load_all_fundamentals

dfs = load_all_fundamentals()
df_z = compute_fundamental_zscores(dfs)
df_returns = get_all_returns_fundamental(df_z)

df_returns

Fetching prices for AIR.PA...
YF.download() has changed argument auto_adjust default to True
Error fetching AIR.PA: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for SAF.PA...
Error fetching SAF.PA: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for HO.PA...
Error fetching HO.PA: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for MTX.DE...
Error fetching MTX.DE: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for LDO.MI...
Error fetching LDO.MI: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for RR.L...
Error fetching RR.L: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for BA.L...
Error fetching BA.L: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for BA...
Error fetching BA: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for RTX...
Error fetching RTX: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for LMT...
Error fetching LMT: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for NOC...
Error fetching NOC: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for GD...
Error fetching GD: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for TXT...
Error fetching TXT: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for HWM...
Error fetching HWM: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for SPR...
Error fetching SPR: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for HEI...
Error fetching HEI: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for TDG...
Error fetching TDG: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for BBD-B.TO...
Error fetching BBD-B.TO: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for CAE.TO...
Error fetching CAE.TO: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for ERJ...
Error fetching ERJ: 'DataFrame' object has no attribute 'to_frame'
Fetching prices for AVAV...
Error fetching AVAV: 'DataFrame' object has no attribute 'to_frame'

KeyError: 'Date'

In [6]:
import pandas as pd
df_returns.head(30)
df_returns['date'] = pd.to_datetime(df_returns['Date'])
df_returns

Price       Date  ticker    return       date
0     2020-01-01  AIR.PA       NaN 2020-01-01
1     2020-02-01  AIR.PA -0.188682 2020-02-01
2     2020-03-01  AIR.PA -0.451064 2020-03-01
3     2020-04-01  AIR.PA -0.024604 2020-04-01
4     2020-05-01  AIR.PA -0.020387 2020-05-01
...          ...     ...       ...        ...
1255  2024-08-01    AVAV  0.141257 2024-08-01
1256  2024-09-01    AVAV -0.015999 2024-09-01
1257  2024-10-01    AVAV  0.072120 2024-10-01
1258  2024-11-01    AVAV -0.095181 2024-11-01
1259  2024-12-01    AVAV -0.208792 2024-12-01

[1260 rows x 4 columns]

In [4]:
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))

if project_root not in sys.path:
    sys.path.insert(0, project_root)

from src.data.compute_zscores import compute_fundamental_zscores
from src.data.load_data import load_all_fundamentals, get_all_returns_fundamental

dfs = load_all_fundamentals()
df_z = compute_fundamental_zscores(dfs)

In [5]:
df_result = get_all_returns_fundamental(df_z)
df_result

          date  ticker    return
0   2021-12-31  AIR.PA  0.002241
1   2022-12-31  AIR.PA  0.276976
2   2023-12-31  AIR.PA  0.221348
3   2024-03-31  AIR.PA -0.244091
4   2024-06-30  AIR.PA  0.023078
..         ...     ...       ...
115 2024-12-31     ERJ  0.259542
116 2024-01-31    AVAV  0.324519
117 2024-04-30    AVAV  0.117342
118 2024-07-31    AVAV  0.203988
119 2024-10-31    AVAV -0.161937

[120 rows x 3 columns]